### ISSUE TITLE
Flags of US and UK subregions needed

### ISSUE THREAD

**Issue by roozbehp** [behdad/region-flags#5] opened 2015-07-19 20:48 UTC
Unicode is considering adding support for subregional flags.

My guess is the most in-demand are going to be the US states, and the four UK countries.

Spelling it out, it's actually 51 US subregions (including DC).

The list for US is at https://www.iso.org/obp/ui/#iso:code:3166:US (exclude those saying "outlying area", which already have a BCP47 code).

The list for UK is at https://www.iso.org/obp/ui/#iso:code:3166:GB. We only need the three countries and the one province:

GB-ENG: England
GB-NIR: Northern Ireland
GB-WLS: Wales
GB-SCT: Scotland

**Comment by shervinafshar** [comment] 2015-07-19 21:58
I implemented this a while back and there is a [pull request](https://github.com/behdad/region-flags/pull/4) for this which Behdad need to verify and merge.

**Comment by behdad** [comment] 2015-08-08 08:21
Closing as dupe of https://github.com/behdad/region-flags/pull/4

**Closed as completed by behdad** 2015-08-08 08:21 UTC
